### ISSUE TITLE
importing annotations from future causes an exception to occur when calling avro_schema()

### ISSUE THREAD

**Issue by nhuber-tc** [marcosschroh/dataclasses-avroschema#96]
**Describe the bug**
doing a `from __future__ import annotations` in a file that defines an AvroModel makes it raise an exception when you call `avro_schema()`

**To Reproduce**
```
from __future__ import annotations

from dataclasses_avroschema import AvroModel
from dataclasses import dataclass


@dataclass
class A(AvroModel):
    foo: str

print(A.avro_schema())
```
This raises `AttributeError: 'str' object has no attribute 'avro_schema_to_python'`. Note that the example here doesn't actually use any features needed from that import but in my case I was adding a custom constructor as a class method and specifying the return type.

**Expected behavior**
Using the annotations feature from `__future__` shouldn't impact this library.

**Comment by marcosschroh** [comment]
HI @nhuber-tc ,

Thanks for reporting the issue. I will have to take a look but `annotations` is doing, but this library is prepared to work with `dataclasses` (`python 3.7` or greater), so `annotations` are not need it.  Which python version are you using?

**Comment by nhuber-tc** [comment]
I'm using Python 3.8, annoations are needed if you want to do something like

```
class A
    @classmethod
    def make_a(cls) -> A
        return A()
```

the reference to A on line 3 would be an error if you didn't import annotations from future, otherwise you can wrap it in strings like 'A'. I had my AvroModel dataclass defined in the same file that was using this functionality and it was very unexpected to run into. See https://www.python.org/dev/peps/pep-0563/. It sounds like this behaviour will become the default in Python 3.10 so it may become a problem without this import once that version is released.

**Comment by marcosschroh** [comment]
Usually I resolve this issue using the class name between quotes or `typing.Type["MyClassName"]. I will try to take a look but seems a hard task because I have to inspect the module. Are you blocked for this ?

**Comment by nhuber-tc** [comment]
No, I'm not blocked by this. I was able to refactor my design when I ran into this, once I figured out what was causing it, to not have it be a problem anymore.

**Comment by marcosschroh** [comment]
Cool, thanks. I found the issue. The code `from __future__ import annotations` makes `dataclasses.Field.type` return always  a `string` instead of a `type`. In python 3.10 resolving this issue is really easy, because I know that `annotations` will be the default behaviour and `type(dataclasses.Field.type)` will return the proper `type`. In python < 3.10 is super hard because I need to know whether the user is doing `from __future__ import annotations` for every module. Here is open python issue: https://bugs.python.org/issue39442

Let's keep this issue open for the future migration to Python 3.10

**Comment by marcosschroh** [comment]
Closing this issue because of the last recommendation:

```
  Do not use from future import annotations when you need actual type object.
  This option won't be default. So no plan to fix it.

  PEP 649 will be accepted, but you can not use it for now.
```
